language: cpp

compiler:
  - gcc

before_install:
  - export TUNDRA_DIR=$PWD
  - cd ~/
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
  - tar -zxvf cmake-2.8.12.2.tar.gz
  - cd cmake-2.8.12.2
  - ./configure --prefix=/usr --no-qt-gui
  - sudo make -s install

install:
  - cd $TUNDRA_DIR/tools/Linux
  - ./build-deps.bash --depsonly
  - cd ../../../naali-deps
  - export NAALI_DEP_PATH=$PWD

before_script:
  - cd $TUNDRA_DIR
  - cmake -DCMAKE_MODULE_PATH=$NAALI_DEP_PATH/lib/SKYX/cmake .

script:
  - make
  - sudo make install
